### ISSUE TITLE
Question about the metric PTQ

### ISSUE THREAD

**Issue by shwoo1219** [robot-learning-freiburg/Panoptic-Tracking#1]
Thanks for your code!

I have a question on the metric PTQ.
If my understanding is correct, I see that PTQ measures TP, FP, FN, IoU of TP in a frame-level, and penalizes IoU of TP if instance ID tracking fails.
In that case, I wonder what happens in the following cases.
 
(Category_id, Track_id)
GT          (1,1) (1,1) (1,1)
1 case PRED (1,1) (1,2) (1,2)
2 case PRED (1,1) (2,_) (2,_)

Under perfect mask prediction (i.e, IoU between predicted segment and ground truth segment is 1), we get the following PTQ scores for each case.

PTQ of 1 case: (3-2) / 3 => 1/3
PTQ of 2 case: 1 / (1+0.5*2) => 1/2

Is this correct? or am I missing something?

Thanks,

**Comment by mohan1914** [comment]
I am assuming when you say category_id you mean the class and I am also assuming that you are computing PTQ for class 1 only

In the first case, the IDS will be just 1 and not 2. Since from frame 2 to frame 3 track id remains the same i.e 2
PTQ of 1st case: (3-1) / 3 => 2/3

In the second case,
PTQ of 2nd case: 1/ (1+0.5*2) => 1/2

**Comment by shwoo1219** [comment]
Thanks for your quick reply.

Yes, I was considering the case of computing PTQ for class 1 with 3 consecutive **gt** and **pred** frames.

For the second case, I was actually curious about when the class label prediction failed (FN for class 1).
Here, you mean that we also consider this as a tracking failure.
Then, how can we compute the sPTQ in this case, as we can not get the segment IoU.

Thanks,

**Comment by mohan1914** [comment]
Sorry, for the confusion. IDS is only computed for matched segments i.e TP. I have updated my earlier comment.

**Comment by shwoo1219** [comment]
Thanks
